services:
  grafana-lgtm:
    image: 'grafana/otel-lgtm:latest'
    ports:
      - '3000:3000'
      - '4317:4317'
      - '4318:4318'
  postgres:
    image: 'postgres:latest'
    container_name: 'SprintLiteDB'
    environment:
      - 'POSTGRES_DB=SprintLite'
      - 'POSTGRES_PASSWORD=SprintLitePassword'
      - 'POSTGRES_USER=SprintLite'
    ports:
      - '5000:5432'
    volumes:
      - C:\Docker_Container\Postgres\SprintLite:/var/lib/postgresql

