spring.application.name=SprintLite

############ Start PostgresDB Section ####################

spring.datasource.url=jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5000}/${DATABASE_NAME:SprintLite}
spring.datasource.username=${DATABASE_USERNAME:SprintLite}
spring.datasource.password=${DATABASE_PASSWORD:SprintLitePassword}
spring.jpa.show-sql=${SHOW_SQL:true}
spring.jpa.properties.hibernate.format_sql=${HIBERNATE_FORMAT_SQL:true}
spring.jpa.properties.hibernate.default_batch_fetch_size = ${DEFAULT_BATCH_FETCH_SIZE:50}
#spring.jpa.hibernate.ddl-auto=create

############ End PostgresDB Section ####################

############ Start Spring Security Section ####################

spring.security.user.name=SprintLite
spring.security.user.password=SprintLite@123
#spring.security.user.roles=USER,ADMIN

############ End Spring Security Section ####################

############ Start CORS Section ####################

app.cors.allowed-origins=http://localhost:5173,https://dev.sprintlite.com
app.cors.allowed-methods=*
app.cors.allowed-headers=*
app.cors.allow-credentials=true
app.cors.max-age=3600

############ End CORS Section ####################

############ Start Actuator Section ####################

management.endpoint.health.show-details=always
management.server.port=9090
management.endpoints.web.base-path=/sprintlite/actuator
management.endpoints.web.exposure.include=*
#management.endpoints.web.exposure.exclude=beans
management.endpoint.configprops.show-values=always
management.endpoint.env.show-values=always
# Allows remote shutdown
management.endpoint.shutdown.access=unrestricted
management.info.env.enabled=true
info.app.name=${spring.application.name}
info.app.description=Backend Project for SprintLite application
info.app.version=1.0.0
info.app.contact.email=support@sprintlite.com
info.developer.name=SprintLite

############ End Actuator Section ####################

############ Start OTLP Section ####################

management.otlp.metrics.export.url=http://localhost:4318/v1/metrics
management.otlp.metrics.export.step=10s
management.opentelemetry.tracing.export.otlp.endpoint=http://localhost:4318/v1/traces
management.tracing.sampling.probability=1.0
management.opentelemetry.logging.export.otlp.endpoint=http://localhost:4318/v1/logs

############ End OTLP Section ####################
